spring:
  sql:
    init:
      schema-locations: classpath:schemas/schema-h2db.sql
      mode: always
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:1b
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      client:
        enabled: false
  datasource:
    primary:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: h2
      password: h2
      console:
        enabled: true
    secondary:
      jdbc-url: jdbc:postgresql://localhost:5432/inventory
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG